### ISSUE TITLE
reportUnknownVariableType error notification by pyright

### ISSUE THREAD

**Issue by jcamatta** [reagento/dishka#182]
Hi

## Context
I use very often static type checkers of python, like pyright.
Recently I installed this library and got the **reportUnknownVariableType error**.

Here is an image of notification

![image](https://github.com/user-attachments/assets/6eceeef6-2437-44c6-a112-20ea3aae461b)

Is mainly due to the context parameter which is defined as dict only. So, this provokes the Unknown error.

## Proposal
Since the context should receive a type and an instance, I suggest to create a subtype like this:

```
from typing import TypeVar

T = TypeVar("T")

def func(context: dict[type[T], T]) -> None:
    pass

func({int: 1}) # <- 0 error
func({str: 1}) # <- error
```

what do you think?

<hr>

## Enviroment configuration
I was using **dishka-1.2.0**

This was my project.toml pyright config:

[tool.pyright]
include = ["code"]
exclude = ["projects"]
pythonVersion = "3.10"
pythonPlatform = "Linux"
strict = ["**"]

**Comment by Tishka17** [comment]
I agree, we need to specify it explicitly as dict[Any, Any]

**Comment by jcamatta** [comment]
this doesn't work "dict[type[T], T]", right?

**Comment by Tishka17** [comment]
No, It doesn't work:
https://github.com/python/mypy/issues/4717

Waiting for https://discuss.python.org/t/typeform-spelling-for-a-type-annotation-object-at-runtime/51435/8
