### ISSUE TITLE
AsgiFastSteam integration support

### ISSUE THREAD

**Issue by Forceres** [reagento/dishka#251]
Add AsgiFastStream type for setup_dishka

**Comment by Lancetnik** [comment]
It should works already due **AsgiFastStreamm** is direct **FastStream** inheritor, but I have to check

**Comment by Forceres** [comment]
> It should works already due **AsgiFastStreamm** is direct **FastStream** inheritor, but I have to check

Yeah, it works, but code editor complains on types

**Comment by Sehat1137** [comment]
@Forceres what version FastStream are you using?

**Comment by Forceres** [comment]
> @Forceres what version FastStream are you using? Try updating to version 0.5.25

Already used 0.5.25

**Comment by Sehat1137** [comment]
@Forceres 

Try to use setup_dishka for ur FastStream app and after this call method as_asgi for u app

**Comment by Forceres** [comment]
> @Forceres
> 
> Try to use setup_dishka for ur FastStream app and after this call method as_asgi for u app

Thanks, it works!
