### ISSUE TITLE
[feature request] hint scope/provider for from_context errors on mismatch

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [reagento/dishka#260]
while experimenting with adding a new from_context provider, i accidentally added it to a provider of the the wrong scope

the error didn't hint at the scope it searched at

in case a context var is missing, it would be very helpful to check the scopes available and include a scope where it is available
as well as the scope that was being looked at 

aka instead of `ǸotFound for AvaliablePlugins` i'd like to see `ÀvaliablePlugins not found in scope Request, its available in scope APP, the provider is configured in ....`

**Comment by Tishka17** [comment]
You can try a version from current develop branch, we have improved logging here. If it is still not enough, please describe more
