### ISSUE TITLE
AnyOf["SomeObject", "AnotherObject"] don't work

### ISSUE THREAD

**Issue by Maclovi** [reagento/dishka#290]
I tried to specify types via strings but it gives an error.
MRE:
```python
@provide(scope=Scope.REQUEST)
async def new_async_session(
    self, session_factory: async_sessionmaker[AsyncSession]
) -> AsyncIterator[AnyOf["AsyncSession", "UoWProtocol"]]:
    async with session_factory() as session:
        yield session
```
Error:
```dishka.exceptions.GraphMissingFactoryError: Cannot find factory for (<class 'sqlalchemy.ext.asyncio.session.AsyncSession'>, component=''). It is missing or has invalid scope.```

**Comment by Tishka17** [comment]
Though it cannot be probably fixed, we should at least detect this and raise an error with a recommendation to replace with `"AnyOf[AsyncSession, UoWProtocol]"`
