### ISSUE TITLE
request for benchmark file

### ISSUE THREAD

**Issue by raceychan** [reagento/dishka#313]
Hi, 

This is the author of ididi(https://github.com/raceychan/ididi) Here,
recently I have been trying to make a benchmark comparing performance difference between different DI libs in python.

A few days ago, I had an inspiring conversation with tishka
[Tishka reddit comment](https://www.reddit.com/r/Python/comments/1gn5erp/comment/lx3tze8/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) on reddit, 
I wonder if there is a benchmark test file that I can follow.

There is this benchmark file with 122 classes in ididi test suits [test_data.py](https://github.com/raceychan/ididi/blob/master/tests/test_data.py), where I basically import those classes then resolve them like this

```py
    from ididi import DependencyGraph

    from .test_data import CLASSES

    dg = DependencyGraph()
    pre = time.perf_counter()
    for k, c in CLASSES.items():
        dg.node(c)
    aft = time.perf_counter()
    cost = round(aft - pre, 6)
    print(f"{cost} seoncds to register {len(CLASSES)} classes")
```
I tried to do the same thing with dishka, but I am not sure 
- is there a benchmark file that I can just follow the same test procedure with ididi,
- if there isn't one, is it possible to do it without menually writing providers for all 122 classes

**Comment by Tishka17** [comment]
Hi, I didn't actually prepare benchmarks for serious usage, it was just preliminary testing to ensure that we have no serious problems.

What I see in such tests:
1. Startup time. Either full graph build time or with first request included. 
2. Recreation of same objects in cycle. It is important not to request same cached objects, but actually recreate them. Intermediate objects should be cached of cause.

As for now, I can share this example: https://gist.github.com/Tishka17/d51e977a2c42b55712fee7772fac2dbd

I also had another with generated dozens of classes, but I need time to prepare it for sharing

**Comment by raceychan** [comment]
> Hi, I didn't actually prepare benchmarks for serious usage, it was just preliminary testing to ensure that we have no serious problems.
> 
> What I see in such tests:
> 
> 1. Startup time. Either full graph build time or with first request included.
> 2. Recreation of same objects in cycle. It is important not to request same cached objects, but actually recreate them. Intermediate objects should be cached of cause.
> 
> As for now, I can share this example: https://gist.github.com/Tishka17/d51e977a2c42b55712fee7772fac2dbd
> 
> I also had another with generated dozens of classes, but I need time to prepare it for sharing

thanks, would help a lot, but one small question from the gist:

with_raw.py 
    for x in range(NUMBER*10):

with_dishka.py
def main():
    container = make_container(MyProvider(), scopes=MyScope)
    for x in range(NUMBER):

it is supposed to be tested at different scale or any specific reason for this?

**Comment by Tishka17** [comment]
It is just a mistake.
