### ISSUE TITLE
provide a context manager variant of make_*container

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [reagento/dishka#318]
currently the root container is something that needs extra cleanup after usage

instead of obtaining it with a function, and then later having to call close for full cleanup,
i'd like to have a api that ensures a context for the container is given and can be used with other frameworks context managers

(for example clicks `ctx.with_resource`or `ExitStack.enter_context` )

**Comment by Tishka17** [comment]
Do you mean this?
```python
with contextlib.closing(make_container()) as container:
   ...
```

**Comment by RonnyPfannschmidt** [comment]
In essence its a thing about consistency 

Any sub scope is a context manager but the root isn't

**Comment by Tishka17** [comment]
It was in earlier versions, but we found that it is not useful in real frameworks
