### ISSUE TITLE
How to mock dependencies in tests

### ISSUE THREAD

**Issue by Skorpyon** [reagento/dishka#60]
Hey!

Is it possible override dependecies like it realized in dependency-injector?

```python
with container.api_client_factory.override(unittest.mock.Mock(ApiClient)):
    service2 = container.service_factory()
    assert isinstance(service2.api_client, unittest.mock.Mock)
```

**Comment by Tishka17** [comment]
There are actually to ways to override depedenncy:

1. Pass ins context variable when entering scope. I do not think it is easy to do for REQUEST-scoped dependencies
2. Create another provider and pass it as the last one when creating container. 

In next release it is planned to add methods like `provider.provide` to add factories directly to created provider. But anyway container itself is immutable after creation (there are some plans to implement graph validation which can require it)

**Comment by Tishka17** [comment]
Added some info in documentation (see latest)
