### ISSUE TITLE
Service Repository Pattern Scopes

### ISSUE THREAD

**Issue by theobouwman** [reagento/dishka#67]
I'm moving from the `python-dependency-injector` library to this one and am using a service-repo pattern.
This is my small setup:

```python


class DBProvider(Provider):
    @provide(scope=Scope.APP)
    def engine(self) -> AsyncEngine:
        engine = create_async_engine(
            get_config().ASYNC_DB_URL(),
            echo=True,
        )
        return engine


    @provide(scope=Scope.REQUEST)    
    async def session(self, engine: AsyncEngine) -> AsyncIterable[AsyncSession]:
        async with AsyncSession(engine) as session:
            yield session



class Interactor:
    def __init__(self, session: AsyncSession):
        self.session = session

    def test(self) -> str:
        return "test"
    

class InteractorProvider(Provider):
    i1 = provide(Interactor, scope=Scope.REQUEST)


class ServiceProvider(Provider):
    wallet_pass_api_service = provide(WalletPassApiService, scope=Scope.APP)
    block_user_repo = provide(BlockedUserRepository, scope=Scope.REQUEST)


container = make_async_container(
    DBProvider(), 
    ServiceProvider(),
    InteractorProvider()
)
```

When I use `Scope.APP` with the `block_user_repo` this does not work, as expected, since the BlockedUserRepository` has a dependency on the `AsyncSession` which is a `Scope.REQUEST`.

But shouldn't all repositories and service be initialised on app startup? Because creating, possibly 10 or 20 repositories/services on each request result in large overhead?

**Comment by Tishka17** [comment]
There is actually a question: are you going to pass Session to `__init__` or to repo methods. This is not about IoC-container, it more about your code structure. 
* If you are passing session to repo constructor, then you cannot create it in advance and you cannot use one repo with multiple session.
* If you are passing Session into methods, but not saving it in `self`, that you can create repo only once, but have to manage passing session in you code.
 
So, usually I personally prefer first approach as it is simpler and take less effort.

One more thing here is that if you have 20 services in total, you wont probably use all of them and dishka wont create all of them each time. They are created only by request. So, once you requested some Interactor which requires couple of Repositories, then only that interactor and only those repositories will be created for this request.

And what about speed? No one knows how fast it will be in your case. I can say "Object creation is fast in python" or I can say "function calling is slow in python". Both phrases would be true in different contexts. IoC-container itself slows your program a bit, but it is noticeable only if your program does nothing. So, do benchmarks, try different tricks. If you find out that there is some negative effect on objects recreation, then try `__slots__`, probably that will be enough. But again, benchmarks first. 

For some classes, which have heavy initialization (like loading neural networks or network I/O) I can recommend using Object pool pattern, but I cannot suggest any ready to use solution

**Comment by theobouwman** [comment]
Thanks. Will go with the first option.
