### ISSUE TITLE
FastStream integration

### ISSUE THREAD

**Issue by theobouwman** [reagento/dishka#71]
Hi,

How could one use dishka with FastStream? https://github.com/airtai/faststream

**Comment by IvanKirpichnikov** [comment]
Hello. You need to create your own `inject` decorator. See examples of decorators in the `dishka/integrations` folder

**Comment by Tishka17** [comment]
@theobouwman it is merged and will be available in future version. For now you can just copy the file to your project

https://github.com/reagento/dishka/blob/d210f138a583dc49853e8e82368231da6e7c8e58/src/dishka/integrations/faststream.py

**Comment by theobouwman** [comment]
Great!
